name: Convert to Static HTML and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Removed stlite-desktop as it doesn't exist and isn't needed
    
    - name: Create static HTML version
      run: |
        mkdir -p static_build
        
        # Read the actual main.py file content
        MAIN_PY_CONTENT=$(cat main.py | sed 's/"/\\"/g' | sed 's/$/\\n/' | tr -d '\n')
        
        # Create a simple HTML wrapper for your Streamlit app
        cat > static_build/index.html << EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>EcoWise Living Platform</title>
            <script src="https://cdn.jsdelivr.net/npm/@stlite/mountable@0.31.0/build/stlite.js"></script>
            <style>
                body {
                    margin: 0;
                    padding: 0;
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                }
                #stlite-main {
                    height: 100vh;
                    width: 100vw;
                }
                .loading {
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    height: 100vh;
                    font-size: 18px;
                    color: #666;
                }
                .loading::after {
                    content: '';
                    width: 20px;
                    height: 20px;
                    border: 2px solid #f3f3f3;
                    border-top: 2px solid #666;
                    border-radius: 50%;
                    animation: spin 1s linear infinite;
                    margin-left: 10px;
                }
                @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
            </style>
        </head>
        <body>
            <div id="stlite-main">
                <div class="loading">Loading EcoWise Living Platform...</div>
            </div>
            
            <script>
                const requirements = [
                    "streamlit==1.31.1",
                    "pandas==2.2.0",
                    "numpy==1.26.3",
                    "matplotlib==3.8.2",
                    "plotly==5.18.0",
                    "Pillow==10.2.0",
                    "requests==2.31.0",
                    "scikit-learn==1.4.0",
                    "seaborn==0.13.2"
                ];
                
                // Get all Python files in the repository
                const files = {};
                
                // Add main.py content (you'll need to replace this with actual content)
                files["main.py"] = \`$(cat main.py | sed 's/`/\\`/g')\`;
                
                // Add other Python files if they exist
                // files["utils.py"] = \`$(if [ -f utils.py ]; then cat utils.py | sed 's/\`/\\\`/g'; fi)\`;
                
                stlite.mount(
                    {
                        requirements: requirements,
                        entrypoint: "main.py",
                        files: files
                    },
                    document.getElementById("stlite-main")
                );
            </script>
        </body>
        </html>
        EOF
        
        # Copy any static assets
        if [ -d "assets" ]; then
            cp -r assets static_build/
        fi
        
        # Copy any data files
        if [ -d "data" ]; then
            cp -r data static_build/
        fi
        
        # Copy any other necessary files
        if [ -f "requirements.txt" ]; then
            cp requirements.txt static_build/
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './static_build'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
